version: 2.1

jobs:
  build:
    docker:
      - image: justincasetech/gradle:5.6.2
    steps:
      - checkout
      - run: |
          apk add --no-cache ca-certificates
      - restore_cache:
          keys:
            - gradle-DoPmHT-{{ checksum "build.gradle.kts" }}
            - gradle-DoPmHT-
      - run: |
          gradle test
      - save_cache:
          key: gradle-DoPmHT-{{ checksum "build.gradle.kts" }}
          paths: ~/.gradle
      - run:
          command: |
            mkdir -p test-results/junit
            find build/test-results/test/*.xml -type f -exec cp {} test-results/junit \;
          when: always
      - store_test_results:
          path: test-results
